services:
  app:
    image: floci/floci:latest
    ports:
      - "4566:4566"
    volumes:
      - data:/app/data
    environment:
      FLOCI_STORAGE_MODE: hybrid
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data

volumes:
  data:
